name: CI

on:
  push:
    branches: [master]
    tags: ["v*"]
  pull_request:
    branches: [master]

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUST_BACKTRACE: short
  RUSTFLAGS: "-D warnings"
  RUSTUP_MAX_RETRIES: 10

jobs:
  hygiene:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Setup | Tools
        run: sudo apt-get install -y protobuf-compiler

      - name: Setup | Cache
        uses: Swatinem/rust-cache@v2

      - name: Build | Hygiene
        run: |
          cargo fmt  -- --check
          cargo clippy --all-features --locked -- -D clippy::all

      - name: Build | Test
        run: |
          cargo test

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Tools
        run: sudo apt-get install -y protobuf-compiler

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup | Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build | Compile
        run: cargo build --all --locked --release

      - name: Build | Name
        run: echo "NAME=helium-wallet-$(git describe --always)-x86-64-linux" >> $GITHUB_ENV

      - name: Build | Package
        run: |
          mkdir $NAME
          mv target/release/helium-wallet $NAME/
          cp README.md $NAME/
          cp LICENSE $NAME/
          tar -zcvf $NAME.tar.gz $NAME/
          sha256sum -b --tag $NAME.tar.gz > $NAME.checksum

      - name: Build | Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: helium-wallet-x86-64-linux
          if-no-files-found: error
          path: helium-wallet-*.tar.gz

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Setup | Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | Tools
        run: brew install protobuf

      - name: Setup | Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup | Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build | Compile
        run: cargo build --all --locked --release

      - name: Build | Name
        run: echo "NAME=helium-wallet-$(git describe --always)-x86-64-macos" >> $GITHUB_ENV

      - name: Build | Package
        run: |
          mkdir $NAME
          mv target/release/helium-wallet $NAME/
          cp README.md $NAME/
          cp LICENSE $NAME/
          gtar -zcvf $NAME.tar.gz $NAME/
          shasum -a 256 -b --tag $NAME.tar.gz > $NAME.checksum

      - name: Build | Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: helium-wallet-x86-64-macos
          if-no-files-found: error
          path: helium-wallet-*.tar.gz

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Setup | Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Setup | Checkout
        uses: actions/checkout@v3

      - name: Setup | LLVM Cache
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ${{ runner.temp }}/llvm
          key: llvm-12.0

      - name: Setup | LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "12.0"
          directory: ${{ runner.temp }}/llvm
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Setup | Protoc
        run: choco install protoc

      - name: Build | Compile
        run: cargo build --all --release --locked

      - name: Build | Name
        run: echo "NAME=helium-wallet-$(git describe --always)-x86-64-win" >> $GITHUB_ENV

      - name: Build | Package
        run: |
          mkdir $env:NAME
          mv target/release/helium-wallet.exe $env:NAME/
          cp README.md $env:NAME/
          cp LICENSE $env:NAME/
          7z a "$env:NAME.zip" "$env:NAME/"
          certUtil -hashfile "$env:NAME.zip" SHA256 > "$env:NAME.checksum"

      - name: Build | Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: helium-wallet-x86-64-win
          if-no-files-found: error
          path: helium-wallet-*.tar.gz

  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: [hygiene, build-linux, build-mac, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Setup | Artifacts
        uses: actions/download-artifact@v3
        with:
          path: helium-wallet-*

      - name: Release | Artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          name: ${{github.ref_name}}
          files: |
            helium-wallet-*.zip
            helium-wallet-*.checksum
